### PR TITLE
add networkx lib

### PR DESCRIPTION
**Pull request by haubourg**
Hello, 
I've added networkx dependency so that some qgis plugins can work

### CODE REVIEW

**Comment by elemoine** [comment]
Can you please add the same to `qgis-exec/Dockerfile` as well?

**Comment by haubourg** [comment]
@elemoine shoudl be fine with 29e69cd69c33fe75bfca0e731197a16541f79304

**Comment by elemoine** [comment]
@haubourg the commit you're referring to does not exist apparently.

I was wondering if this package is necessary for QGIS Server as well? For the QGIS Server plugins I mean.

**Comment by elemoine** [comment]
Anyway, thanks for the change.

And by the way, the docker-qgis repo currently focuses on QGIS Server. I am wondering if merging my desktop branch into the master branch would make sense. I'll think more about it.

**Comment by haubourg** [comment]
I'd  be in favour of separate repositories

**Comment by haubourg** [comment]
mm, I see my commit here https://github.com/haubourg/docker-qgis/commits/ele_desktop_add_networkx I don't understand why it was not seen from the pull request.  

anyway, networkx is only for a desktop plugin for QGEP app, if we focus on the server here, it's not necessary

**Pull request merged**
